add_library(SpiceLib STATIC
    Spice.cpp
    Spice.h
    core/Matrix.h
    core/Matrix.cpp
    core/LU.h
    core/LU.cpp
    mna/MnaSystem.h
    mna/MnaSystem.cpp
    devices/Device.h
    devices/Device.cpp
    devices/Resistor.h
    devices/Resistor.cpp
    devices/CurrentSource.h
    devices/CurrentSource.cpp
    devices/VoltageSource.h
    devices/VoltageSource.cpp
    devices/Diode.h
    devices/Diode.cpp
    devices/Capacitor.h
    devices/Capacitor.cpp
    solver/newton.h
    solver/newton.cpp
    parser/numeric.h
    parser/numeric.cpp
    parser/tokenize.h
    parser/tokenize.cpp
    parser/Circuit.h
    parser/Circuit.cpp
    solver/transient.h
    solver/transient.cpp
    devices/Inductor.cpp
    devices/Inductor.h
    sim/simulate.cpp
    sim/simulate.h
    output/result_writer.cpp
    output/result_writer.h
)

target_include_directories(SpiceLib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
